# iOS targets
[target.aarch64-apple-ios]
rustflags = ["-C", "target-cpu=apple-a14"]

[target.aarch64-apple-ios-sim]
rustflags = ["-C", "target-cpu=apple-a14"]

# Android targets
[target.aarch64-linux-android]
rustflags = ["-C", "target-cpu=cortex-a76"]

[target.armv7-linux-androideabi]
rustflags = ["-C", "target-cpu=cortex-a53"]
