[package]
name = "qasr-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "CLI for q-asr: Qwen3-ASR speech-to-text"

[[bin]]
name = "q-asr"
path = "src/main.rs"

[dependencies]
q-asr = { path = "../qasr" }
